version: '3'

services:

  catalogoga:
    image: pocga/catalogoga
    ports:
     - 4000:4000
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MOCK_URL=http://mockproductos:8080/ProductosMock/AllProductos
    links: 
      - mongodb
    depends_on:
      - mongodb
      - mongoseed
      - mockproductos
    container_name: catalogoga-compose

  mockproductos:
    image: pocga/mockproductos
    container_name: mockproductos-compose
    ports:
      - "8090:8080"

  mongodb:
    image: mongo
    container_name: mongo-compose
    ports:
      - "27017:27017"

  mongoseed:
    image: pocga/mongoseed
    container_name: mongoseed-compose
    links:
      - mongodb

